package edu.cmu.a2.ui;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;

/******************************************************************************
 * File:NewJFrame.java
 * Course: 17655
 * Project: Assignment 2
 * Copyright: Copyright (c) 2009 Carnegie Mellon University
 * Versions:
 *	1.0 November 2009 - Initial rewrite of original assignment 2 (ajl).
 *
 * This class defines a GUI application that allows inventory to be added to the
 * inventory databases. There are tree tables in the inventory database: trees,
 * shrubs, and seeds.
 *
 ******************************************************************************/
/*
 * AddInventoryMainFrame.java
 *
 * Created on Jan 29, 2010, 9:24:23 PM
 */

/**
 *
 * @author lattanze
 */
public class InventoryMainFrame extends javax.swing.JFrame {

       String versionID = "v0.1";

    /** Creates new form AddInventoryMainFrame */
    public InventoryMainFrame() {
        initComponents();
        frameTitleLabel.setText("Inventory Management Application " + versionID);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treesRadioButton = new javax.swing.JRadioButton();
        seedsRadioButton = new javax.swing.JRadioButton();
        shrubsRadioButton = new javax.swing.JRadioButton();
        frameTitleLabel = new javax.swing.JLabel();
        productIdLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        databaseServerIpText = new javax.swing.JTextField();
        productIdText = new javax.swing.JTextField();
        priceText = new javax.swing.JTextField();
        quantityText = new javax.swing.JTextField();
        addItemButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        inventoryScrollPane = new javax.swing.JScrollPane();
        inventoryTextArea = new javax.swing.JTextArea();
        productDescriptionLabel = new javax.swing.JLabel();
        databaseServerIpLabel = new javax.swing.JLabel();
        productDescriptionText = new javax.swing.JTextField();
        listInventoryButton = new javax.swing.JButton();
        deleteItemButton = new javax.swing.JButton();
        decrementButton = new javax.swing.JButton();
        deleteText = new javax.swing.JLabel();
        decrementText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        treesRadioButton.setText("Trees");
        treesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treesRadioButtonActionPerformed(evt);
            }
        });

        seedsRadioButton.setText("Shrubs");
        seedsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedsRadioButtonActionPerformed(evt);
            }
        });

        shrubsRadioButton.setText("Seeds");
        shrubsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shrubsRadioButtonActionPerformed(evt);
            }
        });

        frameTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        frameTitleLabel.setText("EEPs Inventory Management Application");

        productIdLabel.setText("Product ID");

        priceLabel.setText("Price");

        quantityLabel.setText("Quantity");

        databaseServerIpText.setText("localhost");

        productIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIdTextActionPerformed(evt);
            }
        });

        addItemButton.setText("Add Item");
        addItemButton.setActionCommand("jButton1");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        inventoryTextArea.setColumns(20);
        inventoryTextArea.setRows(5);
        inventoryScrollPane.setViewportView(inventoryTextArea);

        productDescriptionLabel.setText("Product Description");

        databaseServerIpLabel.setText("Database Server IP");

        productDescriptionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productDescriptionTextActionPerformed(evt);
            }
        });

        listInventoryButton.setText("List Inventory");
        listInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listInventoryButtonActionPerformed(evt);
            }
        });

        deleteItemButton.setText("Delete Item");
        deleteItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemButtonActionPerformed(evt);
            }
        });

        decrementButton.setText("Decrement");
        decrementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrementButtonActionPerformed(evt);
            }
        });

        deleteText.setText("Deletes item selected from list ");

        decrementText.setText("Decrements inventory count of item selected from the list");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(productIdLabel)
                            .addComponent(productDescriptionLabel)
                            .addComponent(priceLabel)
                            .addComponent(quantityLabel))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(priceText)
                                    .addComponent(quantityText)
                                    .addComponent(productIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(treesRadioButton)
                                    .addComponent(shrubsRadioButton)
                                    .addComponent(seedsRadioButton))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(listInventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deleteItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(decrementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(deleteText)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(decrementText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productDescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inventoryScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(databaseServerIpLabel)
                        .addGap(17, 17, 17)
                        .addComponent(databaseServerIpText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(frameTitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frameTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(databaseServerIpLabel)
                            .addComponent(databaseServerIpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(productDescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(productDescriptionLabel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(treesRadioButton)
                            .addComponent(productIdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shrubsRadioButton)
                            .addComponent(priceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seedsRadioButton)
                            .addComponent(quantityLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteText))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(decrementText)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(listInventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(decrementButton)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inventoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void treesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treesRadioButtonActionPerformed
        treesRadioButton.setSelected(true);
        shrubsRadioButton.setSelected(false);
        seedsRadioButton.setSelected(false);

    }//GEN-LAST:event_treesRadioButtonActionPerformed

    private void shrubsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shrubsRadioButtonActionPerformed
        // TODO add your handling code here:
        treesRadioButton.setSelected(false);
        shrubsRadioButton.setSelected(false);
        seedsRadioButton.setSelected(true);
    }//GEN-LAST:event_shrubsRadioButtonActionPerformed

    private void seedsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedsRadioButtonActionPerformed
        // TODO add your handling code here:
        treesRadioButton.setSelected(false);
        shrubsRadioButton.setSelected(true);        
        seedsRadioButton.setSelected(false);
    }//GEN-LAST:event_seedsRadioButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed

        // Adds inventory to database

        Boolean connectError = false;   // Error flag
        Connection DBConn = null;       // MySQL connection handle
        String description;             // Tree, seed, or shrub description
        Boolean executeError = false;   // Error flag
        String errString = null;        // String for displaying errors
        int executeUpdateVal;           // Return value from execute indicating effected rows
        Boolean fieldError = false;     // Error flag
        String msgString = null;        // String for displaying non-error messages
        ResultSet res = null;           // SQL query result set pointer
        String tableSelected = null;    // String used to determine which data table to use
        Integer quantity;               // Quantity of trees, seeds, or shrubs
        Float perUnitCost;              // Cost per tree, seed, or shrub unit
        String productID = null;        // Product id of tree, seed, or shrub
        java.sql.Statement s = null;    // SQL statement pointer
        String SQLstatement = null;     // String for building SQL queries
        
        // Check to make sure a radio button is selected
       
        inventoryTextArea.setText("");
        
        if (!treesRadioButton.isSelected() && !shrubsRadioButton.isSelected() && !seedsRadioButton.isSelected())
        {
            fieldError = true;
            inventoryTextArea.append("\nMust select Tree, Seeds, or Shrubs radio button.");

        } else {
       
            //Make sure there is a product description
            if ( productDescriptionText.getText().length() == 0 )
            {
                fieldError = true;
                inventoryTextArea.append("\nMust enter a product description.");
                
            } else {
     
                //Make sure there is a product ID
                if ( productIdText.getText().length() == 0 )
                {
                    fieldError = true;
                    inventoryTextArea.append("\nMust enter a product ID.");
                } else {
            
                    //Make sure there is a price
                    if ( priceText.getText().length() == 0 )
                    {
                        fieldError = true;
                        inventoryTextArea.append("\nMust enter a product price.");
                    } else {
                    
                        //Make sure quantity is specified
                        if ( quantityText.getText().length() == 0 )
                        {
                            fieldError = true;
                            inventoryTextArea.append("\nMust enter a product quantity.");
                        } // quantity
                    } // price
                } // product ID
            } //product description
        } //category selected

        //Now, if there was no error in the data fields, we try to
        //connect to the database.
        
        if ( !fieldError )
        {
            try
            {
                msgString = ">> Establishing Driver...";
                inventoryTextArea.setText("\n"+msgString);

                //load JDBC driver class for MySQL
                Class.forName( "com.mysql.jdbc.Driver" );

                msgString = ">> Setting up URL...";
                inventoryTextArea.append("\n"+msgString);

                //define the data source
                String SQLServerIP = databaseServerIpText.getText();
                String sourceURL = "jdbc:mysql://" + SQLServerIP + ":3306/inventory";

                msgString = ">> Establishing connection with: " + sourceURL + "...";
                inventoryTextArea.append("\n"+msgString);

                //create a connection to the db
                DBConn = DriverManager.getConnection(sourceURL,"remote","remote_pass");

            } catch (Exception e) {

                errString =  "\nProblem connecting to database:: " + e;
                inventoryTextArea.append(errString);
                connectError = true;

            } // end try-catch
        } // fieldError check

        //If there is not connection error, then we form the SQL statement
        //and then execute it.

        if (!connectError && !fieldError )
        {
            try
            {
                // get the data from the text fields
                description = productDescriptionText.getText();
                productID = productIdText.getText();
                quantity = Integer.parseInt(quantityText.getText());
                perUnitCost = Float.parseFloat(priceText.getText());

                // create an SQL statement variable and create the INSERT
                // query to insert the new inventory into the database

                s = DBConn.createStatement();

                // if trees are selected then insert inventory into trees
                // table
                if (treesRadioButton.isSelected())
                {
                    SQLstatement = ( "INSERT INTO trees (product_code, " +
                            "description, quantity, price) VALUES ( '" +
                            productID + "', " + "'" + description + "', " +
                            quantity + ", " + perUnitCost + ");");
                    
                    tableSelected = "TREES";

                }

                // if shrubs are selected then insert inventory into strubs
                // table
                if (shrubsRadioButton.isSelected())
                {
                    SQLstatement = ( "INSERT INTO shrubs (product_code, " +
                            "description, quantity, price) VALUES ( '" +
                            productID + "', " + "'" + description + "', " +
                            quantity + ", " + perUnitCost + ");");
                    
                    tableSelected = "SHRUBS";
                }

                // if seeds are selected then insert inventory into seeds
                // table
                if (seedsRadioButton.isSelected())
                {
                    SQLstatement = ( "INSERT INTO seeds (product_code, " +
                            "description, quantity, price) VALUES ( '" +
                            productID + "', " + "'" + description + "', " +
                            quantity + ", " + perUnitCost + ");");
                    
                    tableSelected = "SEEDS";
                }

                // execute the update
                executeUpdateVal = s.executeUpdate(SQLstatement);

                // let the user know all went well

                inventoryTextArea.append("\nINVENTORY UPDATED... The following was added to the " + tableSelected + " inventory...\n");
                inventoryTextArea.append("\nProduct Code:: " + productID);
                inventoryTextArea.append("\nDescription::  " + description);
                inventoryTextArea.append("\nQuantity::     " + quantity);
                inventoryTextArea.append("\nUnit Cost::    " + perUnitCost);

            } catch (Exception e) {

                errString =  "\nProblem adding inventory:: " + e;
                inventoryTextArea.append(errString);
                executeError = true;

            } // try

        } //execute SQL check

    }//GEN-LAST:event_addItemButtonActionPerformed

    private void listInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listInventoryButtonActionPerformed
        // This button will list the inventory for the product selected by the
        // radio button

        Boolean connectError = false;   // Error flag
        Connection DBConn = null;       // MySQL connection handle
        Boolean executeError = false;   // Error flag
        String errString = null;        // String for displaying errors
        Boolean fieldError = true;      // Error flag
        String msgString = null;        // String for displaying non-error messages
        ResultSet res = null;           // SQL query result set pointer
        String tableSelected = null;    // String used to determine which data table to use
        java.sql.Statement s = null;    // SQL statement pointer

        // Check to make sure a radio button is selected
        if (treesRadioButton.isSelected() || shrubsRadioButton.isSelected() || seedsRadioButton.isSelected())
        {
            fieldError = false;

        } else {

            msgString = "Must select Tree, Seeds, or Shrubs radio button.";
            inventoryTextArea.setText("\n"+msgString);
        }


        //Now, we try to connect to the inventory database.
        if (!fieldError)
        {
            //Clear the fields - they are not needed and may cause confusion
            productIdText.setText("");
            priceText.setText("");
            quantityText.setText("");
            productDescriptionText.setText("");
            inventoryTextArea.setText("");
            
            try
            {
                msgString = ">> Establishing Driver...";
                inventoryTextArea.setText("\n"+msgString);

                //load JDBC driver class for MySQL
                Class.forName( "com.mysql.jdbc.Driver" );

                msgString = ">> Setting up URL...";
                inventoryTextArea.append("\n"+msgString);

                //define the data source
                String SQLServerIP = databaseServerIpText.getText();
                String sourceURL = "jdbc:mysql://" + SQLServerIP + ":3306/inventory";

                msgString = ">> Establishing connection with: " + sourceURL + "...";
                inventoryTextArea.append("\n"+msgString);

                //create a connection to the db
                DBConn = DriverManager.getConnection(sourceURL,"remote","remote_pass");

            } catch (Exception e) {

                errString =  "\nProblem connecting to database:: " + e;
                inventoryTextArea.append(errString);
                connectError = true;

            } // end try-catch

        } // fielderror check - make sure a product is selected
    
        //If there is not connection error, then we form the SQL statement
        //and then execute it.

        if (!connectError && !fieldError)
        {
            try
            {
                // create an SQL statement variable and create the INSERT
                // query to insert the new inventory into the database

                s = DBConn.createStatement();

                // now we build a query to list the inventory table contents
                // for the user
                // ... here is the SQL for trees
                if (treesRadioButton.isSelected())
                {
                    res = s.executeQuery( "Select * from trees" );
                    tableSelected = "TREE";
                }
                // ... here is the SQL for shrubs
                if (shrubsRadioButton.isSelected())
                {
                    res = s.executeQuery( "Select * from shrubs" );
                    tableSelected = "SHRUB";
                }
                // ... here is the SQL for seeds
                if (seedsRadioButton.isSelected())
                {
                    res = s.executeQuery( "Select * from seeds" );
                    tableSelected = "SEED";
                }

                // Now we list the inventory for the selected table
                inventoryTextArea.setText("");
                while (res.next())
                {
                    msgString = tableSelected+">>" + res.getString(1) + "::" + res.getString(2) +
                            " :: "+ res.getString(3) + "::" + res.getString(4);
                    inventoryTextArea.append("\n"+msgString);

                } // while

            } catch(Exception e) {

                errString =  "\nProblem with " + tableSelected +" query:: " + e;
                inventoryTextArea.append(errString);
                executeError = true;

            } // try
        }
    }//GEN-LAST:event_listInventoryButtonActionPerformed

    private void deleteItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemButtonActionPerformed
        // Deletes an item from the database
        
        int beginIndex;                     // Parsing index
        int endIndex;                       // Parsing index
        String productID = null;            // Product ID pnemonic
        Boolean IndexNotFound;              // Flag indicating a string index was not found.
        Boolean connectError = false;       // Error flag
        Connection DBConn = null;           // MySQL connection handle
        String errString = null;            // String for displaying errors
        int executeUpdateVal;               // Return value from execute indicating effected rows
        String msgString = null;            // String for displaying non-error messages
        String tableSelected = null;        // String used to determine which data table to use
        java.sql.Statement s = null;        // SQL statement pointer
        String SQLstatement = null;         // String for building SQL queries
        String inventorySelection = null;   // Inventory text string selected by user
        IndexNotFound = false;              // Flag indicating that a string index was not found
        
        // this is the selected line of text
        inventorySelection =  inventoryTextArea.getSelectedText();

        // make sure the selection is not blank
        if ( inventorySelection != null )
        {
            // get the product ID - here we get the leading index
            beginIndex = 0;
            endIndex = inventorySelection.indexOf(">>",beginIndex);

            if (endIndex < 0 ) {
                IndexNotFound = true;
            } else {
                beginIndex = endIndex+2; //skip past ">>"                                
            }
            
            if ( !IndexNotFound )
            {
                // Here we get the trailing index and parse out the productID
                endIndex = inventorySelection.indexOf(":",beginIndex);

                if (endIndex < 0 ) {
                    IndexNotFound = true;
                } else {
                    productID = inventorySelection.substring(beginIndex,endIndex);
                }              
            }
           
            // Now we delete the inventory item indicated by the productID we
            // parsed out above from the indicated table.
            
            if ( !IndexNotFound )
            {
                inventoryTextArea.setText("");
                inventoryTextArea.append( "Deleting ProductID: " + productID );

                // set up a connection to the LeafTech database
                try
                {                
                    //load JDBC driver class for MySQL
                    Class.forName( "com.mysql.jdbc.Driver" );

                    //define the data source
                    String SQLServerIP = databaseServerIpText.getText();
                    String sourceURL = "jdbc:mysql://" + SQLServerIP + ":3306/inventory";

                    //create a connection to the db
                    DBConn = DriverManager.getConnection(sourceURL,"remote","remote_pass");

                } catch (Exception e) {

                    errString =  "\nProblem connecting to database:: " + e;
                    inventoryTextArea.append(errString);
                    connectError = true;

                } // end try-catch
                
                //If there is no connection error, then we form the SQL statement
                //to delete the inventory item and then execute it.

                if (!connectError )
                {
                    try
                    {
                        s = DBConn.createStatement();

                        // if trees inventory selected
                        if (treesRadioButton.isSelected())
                        {
                            SQLstatement = ( "DELETE FROM trees WHERE product_code = '" + productID + "';");
                        }

                        // if shrubs inventory selected
                        if (shrubsRadioButton.isSelected())
                        {
                            SQLstatement = ( "DELETE FROM shrubs WHERE product_code = '" + productID + "';");
                        }

                        // if seeds inventory selected
                        if (seedsRadioButton.isSelected())
                        {
                            SQLstatement = ( "DELETE FROM seeds WHERE product_code = '" + productID + "';");
                        }
   
                        // execute the delete query
                        
                        executeUpdateVal = s.executeUpdate(SQLstatement);

                        // let the user know all went well
                        
                        inventoryTextArea.append("\n\n" + productID + " deleted...");
                        inventoryTextArea.append("\n Number of items deleted: " + executeUpdateVal );


                    } catch (Exception e) {

                        errString =  "\nProblem with delete:: " + e;
                        inventoryTextArea.append(errString);

                    } // try
               
                } // connection check    
                                       
            } else {

                inventoryTextArea.setText("");
                inventoryTextArea.append("\nNo items selected...\nSELECT ENTIRE INVENTORY LINE TO ADD ITEM TO ORDER\n(TRIPLE CLICK ITEM LINE)");      

            }
        } else {

            inventoryTextArea.setText("");
            inventoryTextArea.append("\nNo items selected...\nSELECT ENTIRE INVENTORY LINE TO ADD ITEM TO ORDER\n(TRIPLE CLICK ITEM LINE)"); 

        } // Blank string check        
        
    }//GEN-LAST:event_deleteItemButtonActionPerformed

    private void decrementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrementButtonActionPerformed
        // Decrements the inventory count for a selected item
        int beginIndex;                     // Parsing index
        int endIndex;                       // Parsing index
        String productID = null;            // Product ID pnemonic
        Boolean IndexNotFound;              // Flag indicating a string index was not found.
        Boolean connectError = false;       // Error flag
        Connection DBConn = null;           // MySQL connection handle
        String errString = null;            // String for displaying errors
        int executeUpdateVal;               // Return value from execute indicating effected rows
        String msgString = null;            // String for displaying non-error messages
        ResultSet res = null;               // SQL query result set pointer
        String tableSelected = null;        // String used to determine which data table to use
        java.sql.Statement s = null;        // SQL statement pointer
        String SQLstatement1 = null;        // String for building SQL queries
        String SQLstatement2 = null;        // String for building SQL queries
        String inventorySelection = null;   // Inventory text string selected by user
        IndexNotFound = false;              // Flag indicating that a string index was not found
        
        // this is the selected line of text
        inventorySelection =  inventoryTextArea.getSelectedText();

        // make sure the selection is not blank
        if ( inventorySelection != null )
        {
            // get the product ID - here we get the leading index
            beginIndex = 0;
            endIndex = inventorySelection.indexOf(">>",beginIndex);

            if (endIndex < 0 ) {
                IndexNotFound = true;
            } else {
                beginIndex = endIndex+2; //skip past ">>"                                
            }
            
            if ( !IndexNotFound )
            {
                // Here we get the trailing index and parse out the productID
                endIndex = inventorySelection.indexOf(":",beginIndex);

                if (endIndex < 0 ) {
                    IndexNotFound = true;
                } else {
                    productID = inventorySelection.substring(beginIndex,endIndex);
                }              
            }
           
            // Now we decrement the inventory count of the item indicated by the productID we
            // parsed out above from the indicated table.
            
            if ( !IndexNotFound )
            {
                inventoryTextArea.setText("");
                inventoryTextArea.append( "Deleting ProductID: " + productID );

                // set up a connection to the LeafTech database
                try
                {                
                    //load JDBC driver class for MySQL
                    Class.forName( "com.mysql.jdbc.Driver" );

                    //define the data source
                    String SQLServerIP = databaseServerIpText.getText();
                    String sourceURL = "jdbc:mysql://" + SQLServerIP + ":3306/inventory";

                    //create a connection to the db
                    DBConn = DriverManager.getConnection(sourceURL,"remote","remote_pass");

                } catch (Exception e) {

                    errString =  "\nProblem connecting to database:: " + e;
                    inventoryTextArea.append(errString);
                    connectError = true;

                } // end try-catch
                
                //If there is no connection error, then we form the SQL statement
                //to decrement the inventory item count and then execute it.

                if (!connectError )
                {
                    try
                    {
                        s = DBConn.createStatement();

                        // if trees inventory selected
                        if (treesRadioButton.isSelected())
                        {
                            SQLstatement1 = ("UPDATE trees set quantity=(quantity-1) where product_code = '" + productID + "';");
                            SQLstatement2 = ("SELECT * from trees where product_code = '" + productID + "';");
                            tableSelected = "TREES";
                        }

                        // if strubs inventory selected
                        if (shrubsRadioButton.isSelected())
                        {
                            SQLstatement1 = ("UPDATE shrubs set quantity=(quantity-1) where product_code = '" + productID + "';");
                            SQLstatement2 = ("SELECT * from shrubs where product_code = '" + productID + "';");
                            tableSelected = "SHRUBS";
                        }

                        // if seeds inventory selected
                        if (seedsRadioButton.isSelected())
                        {
                            SQLstatement1 = ("UPDATE seeds set quantity=(quantity-1) where product_code = '" + productID + "';");
                            SQLstatement2 = ("SELECT * from seeds where product_code = '" + productID + "';");
                            tableSelected = "SEEDS";
                        }

                        // execute the update, then query the BD for the table entry for the item just changed
                        // and display it for the user
                        
                        executeUpdateVal = s.executeUpdate(SQLstatement1);
                        res = s.executeQuery(SQLstatement2);
                       
                        
                        inventoryTextArea.append("\n\n" + productID + " inventory decremented...");
                        
                        while (res.next())
                        {
                            msgString = tableSelected + ">> " + res.getString(1) + " :: " + res.getString(2) +
                            " :: "+ res.getString(3) + " :: " + res.getString(4);
                            inventoryTextArea.append("\n"+msgString);

                        } // while
                        
                        inventoryTextArea.append("\n\n Number of items updated: " + executeUpdateVal );

                    } catch (Exception e) {

                        errString =  "\nProblem with delete:: " + e;
                        inventoryTextArea.append(errString);

                    } // try
               
                } // connection check    
                                       
            } else {

                inventoryTextArea.setText("");
                inventoryTextArea.append("\nNo items selected...\nSELECT ENTIRE INVENTORY LINE TO ADD ITEM TO ORDER\n(TRIPLE CLICK ITEM LINE)");      

            }
        } else {

            inventoryTextArea.setText("");
            inventoryTextArea.append("\nNo items selected...\nSELECT ENTIRE INVENTORY LINE TO ADD ITEM TO ORDER\n(TRIPLE CLICK ITEM LINE)"); 

        } // Blank string check
    }//GEN-LAST:event_decrementButtonActionPerformed

    private void productDescriptionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productDescriptionTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productDescriptionTextActionPerformed

    private void productIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIdTextActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JLabel databaseServerIpLabel;
    private javax.swing.JTextField databaseServerIpText;
    private javax.swing.JButton decrementButton;
    private javax.swing.JLabel decrementText;
    private javax.swing.JButton deleteItemButton;
    private javax.swing.JLabel deleteText;
    private javax.swing.JLabel frameTitleLabel;
    private javax.swing.JScrollPane inventoryScrollPane;
    private javax.swing.JTextArea inventoryTextArea;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton listInventoryButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceText;
    private javax.swing.JLabel productDescriptionLabel;
    private javax.swing.JTextField productDescriptionText;
    private javax.swing.JLabel productIdLabel;
    private javax.swing.JTextField productIdText;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityText;
    private javax.swing.JRadioButton seedsRadioButton;
    private javax.swing.JRadioButton shrubsRadioButton;
    private javax.swing.JRadioButton treesRadioButton;
    // End of variables declaration//GEN-END:variables

}
